### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#284]
Sometimes doesn't open, maybe after the browser is open for a while

**Comment by litzvi** [comment]
might be other pages also don't respond well - like managment->notifications

**Comment by mei309** [comment]
i cannot really check something like this. please send f12 results

**Comment by litzvi** [comment]
nothing in f12, I checked.
It's not responding well especially after it's not used for a few minutes.

**Comment by mei309** [comment]
with what report it happened ?

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/105003407-31e1a400-5a65-11eb-9bbf-a7487ba07d0c.PNG">

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/105003523-563d8080-5a65-11eb-96bd-fb702652485d.PNG">

**Comment by litzvi** [comment]
It's happening in more places, quite often

**Comment by mei309** [comment]
let me know if it happens again. i did something

**Comment by mei309** [comment]
it will probably happen again! i need to happen again so i can find the error.
i set all the logs so hopefully i will know

**Comment by litzvi** [comment]
<img width="1280" alt="Capture1" src="https://user-images.githubusercontent.com/53637868/105331150-b4a16500-5c05-11eb-8c40-e8865380673f.PNG">

**Comment by litzvi** [comment]
<img width="1280" alt="Capture2" src="https://user-images.githubusercontent.com/53637868/105331184-be2acd00-5c05-11eb-8363-8e3db49fbbe2.PNG">

**Comment by litzvi** [comment]
<img width="1280" alt="Capture3" src="https://user-images.githubusercontent.com/53637868/105331223-c71b9e80-5c05-11eb-8d56-b8f36538e974.PNG">

**Comment by litzvi** [comment]
<img width="1280" alt="Capture4" src="https://user-images.githubusercontent.com/53637868/105331242-ce42ac80-5c05-11eb-9fb8-2f9b8b5aa9df.PNG">

**Comment by litzvi** [comment]
[consul_error.log](https://github.com/litzvi/avc-beta/files/5848245/consul_error.log)

**Comment by mei309** [comment]
i think i fixed it. and i uploaded a new version. i did a check. please check it tomorrow morning too so i can see if its still there.
i told eli that if theres problems he should just leave it for tomorrow.
i just need to find that stupid thing.

**Comment by mei309** [comment]
and see in full po details has management button. only the first one. you dont need to check everything .
by me it always works so i cannot really check it.

**Comment by litzvi** [comment]
> and see in full po details has management button. only the first one. you dont need to check everything .
> by me it always works so i cannot really check it.

it doesn't

**Comment by litzvi** [comment]
at the moment I don't have the problem.
In the future don't upload without  full consent..

**Comment by litzvi** [comment]
It still having the previous problem, now refresh doesn't work either. need to open a new one

**Comment by mei309** [comment]
IM CLOSING BECAUSE ELI OPENED 295 ON THE SAME ISSUE
