### ISSUE TITLE
Export report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#489]
![IMG_20210525_181907](https://user-images.githubusercontent.com/53637868/119489429-e2e6ab00-bd85-11eb-94fe-83f3d8940cba.jpg)

**Comment by litzvi** [comment]
com.avc.mis.beta.service.report.LoadingReports.getCashewExportReportRows(LocalDateTime, LocalDateTime)

**Comment by litzvi** [comment]
Apparently QC over here is bad quality that they send on the containers (Maybe it comes from Quality Chocolate, need to ask an Etymologist). So it's not a quality check, it's the bad quality they take out after the roasting or when packing.
We will need to fix the way they put it in and then they can load it and we can show the QC.
Meanwhile, let's get it working without.

**Comment by mei309** [comment]
done but avoided the qc for now

**Comment by litzvi** [comment]
can't see anything

**Comment by mei309** [comment]
look after the controllers and by me only last month they have 2 lines

**Comment by litzvi** [comment]
1. I suggest you put all the container info first, so it can merge (put po after)
2. you forgot commodity, roast and salt
3. they didn't put eta, bag size or bags in box
4. missing bag quantity

**Comment by litzvi** [comment]
would be nice if it fits in the page, there is lots of wasted space

**Comment by mei309** [comment]
> would be nice if it fits in the page, there is lots of wasted space

not managing for now

**Comment by mei309** [comment]
2. theres no roast by you return

**Comment by litzvi** [comment]
> 2. theres no roast by you return

sorry. i added it

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
Where can i set whole, roast and toffee fields? You skipped them in the item setup

**Comment by litzvi** [comment]
I'm talking about the Management -> Item Setup

**Comment by mei309** [comment]
whats the difference between roast and production use roast? same about toffee

**Comment by mei309** [comment]
added whole

**Comment by litzvi** [comment]
> whats the difference between roast and production use roast? same about toffee

CashewItem has these boolean fields - It's not productionUse. It's for classifiyng in the reports if it's roasted or toffee.
e.g. a packed item can be packed but it's roasted and toffee.

**Comment by litzvi** [comment]
[2021-06-01 17-32.pdf](https://github.com/litzvi/avc-beta/files/6675966/2021-06-01.17-32.pdf)

**Comment by mei309** [comment]
i have all they have. i just cannot get the sum of big bags and small bags that they have there

**Comment by mei309** [comment]
i have no way to different them

**Comment by litzvi** [comment]
> i have all they have. i just cannot get the sum of big bags and small bags that they have there

numBags is 1 or not?
directly check if the unit is 50/25lbs or not

**Comment by mei309** [comment]
i will leave it for now.

**Comment by mei309** [comment]
for now all bagQuantity are null

**Comment by mei309** [comment]
and i dont have this info 50/25lbs or not

**Comment by litzvi** [comment]
> and i dont have this info 50/25lbs or not

just because the items where not updated yet

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
1. Ask Eli what to call 'not 25/50', he didn't understand and like it.
I suggest 'bagged item' or 'bagged product'

2. totals in export report don't always show whole and h&p in the same order. I'll attach a screenshot of June report.

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/126853463-39841ceb-b9d6-445b-9882-9eeb011c8755.PNG">

**Comment by mei309** [comment]
1. i asked him.

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
We don't show something indicating it's QC in this report
